DPE-7726 Increase free disk space cleanup timeout (1->3 minutes)
It backports data-platform-workflow commit f1f8d27 to local integration test:
> patch(integration_test_charm.yaml): Increase disk space step timeout (#301)

Otherwise:

> Disk usage before cleanup
> Filesystem      Size  Used Avail Use% Mounted on
> /dev/root        72G   46G   27G  64% /
> tmpfs           7.9G   84K  7.9G   1% /dev/shm
> tmpfs           3.2G  1.1M  3.2G   1% /run
> tmpfs           5.0M     0  5.0M   0% /run/lock
> /dev/sdb16      881M   60M  760M   8% /boot
> /dev/sdb15      105M  6.2M   99M   6% /boot/efi
> /dev/sda1        74G  4.1G   66G   6% /mnt
> tmpfs           1.6G   12K  1.6G   1% /run/user/1001
> Error: The action 'Free up disk space' has timed out after 1 minutes.